###
- hosts: localhost
  connection: local
  vars:
    # homebrew_taps:
      # - homebrew/cask
      # - homebrew/cask-fonts
    homebrew_packages:
      - name: git
      - name: anyenv
      - name: awscli
    homebrew_cask_package:
      # ブラウザ
      - name: google-chrome
      - name: firefox
      - name: arc
      # エディタ
      - name: cursor
      # ターミナル (シェルはzshのまま使う)
      - name: warp
      # 開発ツール
      - name: docker
      - name: sequel-ace
      # コミュニケーション
      - name: zoom
      - name: slack
      # メモ
      - name: notion
      # 電子書籍
      - name: honto
      # マルチディスプレイ
      - name: displaylink
      # 日本語入力
      - name: google-japanese-ime
      # コピペ履歴
      - name: clipy
    apps:
      - { name: "LINE", id: "539883307"}
      - { name: "Focus To-Do", id: "1258530160"}

  tasks:
    - name: setup homebrew
      ignore_errors: yes
      block:
        - name: homebrew update
          homebrew:
            update_homebrew: yes
        # - name: homebrew tap
          # homebrew_tap:
            # name: '{{ item }}'
            # state: present
          # with_items: '{{ homebrew_taps }}'
        - name: homebrew package install
          homebrew:
            name: '{{ item.name }}'
            state: '{{ item.state | default("present") }}'
          with_items: '{{ homebrew_packages }}'

    - name: install from AppStore
      ignore_errors: yes
      block:
        - name: brew install mas
          homebrew:
            name: mas
            state: present
        - name: fetch list
          command: mas list
          register: installed_list
          check_mode: no
          changed_when: no
        - name: install from AppStore
          command: "mas install {{ item.id }}"
          when: "installed_list.stdout_lines | select('search', item.id) | list | length == 0"
          loop: "{{ apps }}"

    - name: homebrew cack package install
      ignore_errors: yes
      community.general.homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_package }}'

    - name: setup anyenv
      block:
        - name: anyenv setting
          file:
            path: '{{ ansible_env.HOME }}/.anyenv/plugins'
            state: directory
        - name: anyenv_update clone
          ansible.builtin.git:
            repo: https://github.com/znz/anyenv-update.git
            dest: '{{ ansible_env.HOME }}/.anyenv/plugins/anyenv-update'

    - name: setup mac dock
      osx_defaults:
        domain: com.apple.dock
        key: '{{ item.key }}'
        type: '{{ item.type }}'
        value: '{{ item.value }}'
      notify: restart_dock
      with_items:
        # hover時に拡大する
        - { key: magnification, type: bool, value: true }
        # 拡大時のサイズ
        - { key: largesize, type: integer, value: 72 }
        # 通常時のサイズ
        - { key: tilesize, type: float, value: 48 }

    - name: setup mac finder
      osx_defaults:
        domain: com.apple.finder
        key: '{{ item.key }}'
        type: '{{ item.type }}'
        value: '{{ item.value }}'
      notify: restart_finder
      with_items:
        # 隠しファイルも表示
        - { key: AppleShowAllFiles, type: bool, value: true }
        # パス表示
        - { key: ShowPathbar, type: bool, value: true }
        # Finderの下の方に「40項目、183.13GB空き」みたいな表示をだすかどうか
        - { key: ShowStatusBar, type: bool, value: true }
        # タブバーを表示
        - { key: ShowTabView, type: bool, value: true }

    - name: setup mac menu bar
      osx_defaults:
        domain={{ item.domain }}
        key={{ item.key }}
        type={{ item.type }}
        value={{ item.value }}
      notify: restart_menu_bar
      with_items:
        # メニューバーのバッテリー表示部分で「%」表示をするかどうか
        - { domain: com.apple.menuextra.battery, key: ShowPercent, type: string, value: "YES" }

        # メニューバーの時計の表示フォーマット
        - { domain: com.apple.menuextra.clock, key: DateFormat, type: string, value: "M\\U6708d\\U65e5(EEE)HH\\:mm\\:ss" }
    
    # その他
    - name: setup mac other
      osx_defaults:
        domain={{ item.domain }}
        key={{ item.key }}
        type={{ item.type }}
        value={{ item.value }}
      with_items:
        # カーソルの移動を速く
        - { domain: com.apple.mouse.scaling, key: NSGlobalDomain, type: float, value: 2.5 }

  handlers:
    - name: restart_dock
      become: yes
      command: killall Dock
    - name: restart_finder
      become: yes
      command: killall Finder
    - name: restart_menu_bar
      become: yes
      command: killall -KILL SystemUIServer
